triggers:
  - keyword: bluetooth

steps:
  - say: Let's try resolve your Bluetooth connectivity.
  - ask: Which type of phone do you have?
    buttons:
      - text: iPhone
        action:
          jump: iphone
      - text: Android
        action:
          jump: android

  - (iphone)
  - tiles:
      - title: iPhone Support
        description: Here are a couple of links to help you troubleshoot.
        buttons:
          - text: Connectivity and Pairing
            url: https://support.whoop.com/hc/en-us/articles/360038028313-WHOOP-Strap-3-0-iOS-Connectivity-and-Pairing
          - text: Heart Rate Broadcast
            url: https://support.whoop.com/hc/en-us/articles/360023430193-How-do-I-connect-WHOOP-Strap-3-0-to-another-device-using-Heart-Rate-Broadcast-
  - jump: confirm

  - (android)
  - tiles:
      - title: Android Support
        description: Here are a couple of links to help you troubleshoot.
        buttons:
          - text: Connectivity and Pairing
            url: https://support.whoop.com/hc/en-us/articles/360025115374-WHOOP-Strap-3-0-Android-Connectivity-and-Pairing
          - text: Frequent Android Disconnects
            url: https://support.whoop.com/hc/en-us/articles/360037136333-Frequent-Android-Disconnects

  - (confirm)
  - delay: 5
  - ask: Still struggling with connectivity?
    buttons:
      - text: Yes
        action:
          end:
            result: true
      - text: No
        action:
          end:
            result: false
